# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x08protocol\"\x1c\n\x0cLoginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"D\n\x0e\x43ommandMessage\x12\x10\n\x08gameType\x18\x01 \x01(\t\x12\x0f\n\x07session\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"2\n\x10StartGameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08gameType\x18\x02 \x01(\t\"C\n\x0eStartGameReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07session\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"S\n\x0fStopGameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08gameType\x18\x02 \x01(\t\x12\x0f\n\x07session\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"1\n\rStopGameReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8c\x02\n\x08\x44ukongGS\x12=\n\x05Login\x12\x16.protocol.LoginRequest\x1a\x18.protocol.CommandMessage\"\x00\x30\x01\x12\x43\n\tStartGame\x12\x1a.protocol.StartGameRequest\x1a\x18.protocol.StartGameReply\"\x00\x12@\n\x08StopGame\x12\x19.protocol.StopGameRequest\x1a\x17.protocol.StopGameReply\"\x00\x12:\n\x04\x43hat\x12\x15.protocol.ChatMessage\x1a\x15.protocol.ChatMessage\"\x00(\x01\x30\x01\x42\x15P\x01Z\x11\x64ukonggs/protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z\021dukonggs/protocol'
  _globals['_LOGINREQUEST']._serialized_start=27
  _globals['_LOGINREQUEST']._serialized_end=55
  _globals['_COMMANDMESSAGE']._serialized_start=57
  _globals['_COMMANDMESSAGE']._serialized_end=125
  _globals['_STARTGAMEREQUEST']._serialized_start=127
  _globals['_STARTGAMEREQUEST']._serialized_end=177
  _globals['_STARTGAMEREPLY']._serialized_start=179
  _globals['_STARTGAMEREPLY']._serialized_end=246
  _globals['_STOPGAMEREQUEST']._serialized_start=248
  _globals['_STOPGAMEREQUEST']._serialized_end=331
  _globals['_STOPGAMEREPLY']._serialized_start=333
  _globals['_STOPGAMEREPLY']._serialized_end=382
  _globals['_CHATMESSAGE']._serialized_start=384
  _globals['_CHATMESSAGE']._serialized_end=428
  _globals['_DUKONGGS']._serialized_start=431
  _globals['_DUKONGGS']._serialized_end=699
# @@protoc_insertion_point(module_scope)
